### ISSUE TITLE
Краш приложения если не убрать клавиатуру.

### ISSUE THREAD

**Issue by The28AWG** [yandex-money/yandex-money-sdk-android#47]
Привет.
Извиняюсь за дурацкий заголовок.
Не нашел описания похожей ошибки, и даже не могу представить из за чего она получается.
<pre>
Process: my-package, PID: 21018
java.lang.NullPointerException: Attempt to invoke interface method 'void android.view.inputmethod.InputConnection.closeConnection()' on a null object reference
        at android.view.inputmethod.InputConnectionWrapper.closeConnection(InputConnectionWrapper.java:270)
        at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:545)
        at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:91)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6312)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:872)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)
</pre>
Как получил ошибку:
1) Совершил оплату на демо счет с помошью тестовой карты 4444 4444 4444 4448.
2) Сохранил данные для возможности повторной оплаты.
3) Снова совершил оплату на эту же карту, но теперь не вводил ее данные, а выбрал ее из списка сохраненных карт (у меня сейчас только одна карта в этом списке, если это важно).
4) При вводе cvv2 кода не закрыл клавиатуру (это важно, если закрыть клавиатуру то приложение не крашится).
5) Нажал кнопку заплатить.

В итоге мне открывается окно сообщением об удачной оплате, но приложение тут же крашится, а в консоле та самая ошибка. Ошибка повторяется всякий раз при повторении пунктов 3, 4, 5.
Что значит не закрыл клавиатуру? Ну просто на экране есть кнопка принудительного скрытия клавиатуры, если нажимаешь ее то все отлично, если клавиатуру не убрать, а сразу нажать на кнопку Заплатить то вылазит ошибка.

Не знаю какая нужна информация для тестирования, у меня телефон LG-K10, но это просто ребрендинг модели LG-M250, вот чуть больше информации:
OS Version: 3.18.35(171101603df55)
OS API Level: 24
Device: mlv5
Model (and Product): LG-M250 (mlv5_global_com)

**Comment by lynnfield** [comment]
Здравствуйте, поправили в рамках ПР #66
