### ISSUE TITLE
NullPointerException: Attempt to invoke virtual method 'void android.view.View.unFocus(android.view.View)' on a null object reference

### ISSUE THREAD

**Issue by afanmatvey** [yandex-money/yandex-money-sdk-android#65]
Последнее время стало часто возникать:

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.unFocus(android.view.View)' on a null object reference
       at android.view.ViewGroup.removeViewInternal(ViewGroup.java:5231)
       at android.view.ViewGroup.removeViewAt(ViewGroup.java:5194)
       at ru.yandex.money.android.fragments.CardsFragment.deleteCard(CardsFragment.java:144)
       at ru.yandex.money.android.fragments.CardsFragment$MenuItemClickListener.onMenuItemClick(CardsFragment.java:171)
       at android.widget.PopupMenu$1.onMenuItemSelected(PopupMenu.java:105)
       at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:761)
       at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:167)
       at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:908)
       at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:898)
       at com.android.internal.view.menu.MenuPopup.onItemClick(MenuPopup.java:128)
       at android.widget.AdapterView.performItemClick(AdapterView.java:318)
       at android.widget.AbsListView.performItemClick(AbsListView.java:1181)
       at android.widget.AbsListView$PerformClick.run(AbsListView.java:3165)
```

Чаще всего на android 7-8, samsung и xiaomi

**Comment by lynnfield** [comment]
Здравствуйте, поправили в рамках ПР #69.
