### ISSUE TITLE
Exception при открытии PaymentActivity

### ISSUE THREAD

**Issue by mitaichik** [yandex-money/yandex-money-sdk-android#7]
Открыл/закрыл/открыл PaymentActivity, в результате словил эксепшн:

```
05-29 13:20:04.163    1518-1518/ru.rzd E/ACRA﹕ ACRA caught a NetworkOnMainThreadException for ru.rzd
    android.os.NetworkOnMainThreadException
            at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1118)
            at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.close(OpenSSLSocketImpl.java:873)
            at com.squareup.okhttp.Connection.closeIfOwnedBy(Connection.java:142)
            at com.squareup.okhttp.OkHttpClient$1.closeIfOwnedBy(OkHttpClient.java:71)
            at com.squareup.okhttp.internal.http.HttpConnection.closeIfOwnedBy(HttpConnection.java:136)
            at com.squareup.okhttp.internal.http.HttpTransport.disconnect(HttpTransport.java:135)
            at com.squareup.okhttp.internal.http.HttpEngine.disconnect(HttpEngine.java:507)
            at com.squareup.okhttp.Call.cancel(Call.java:122)
            at ru.yandex.money.android.PaymentActivity.cancel(PaymentActivity.java:272)
            at ru.yandex.money.android.PaymentActivity.onBackPressed(PaymentActivity.java:183)
            at android.app.Activity.onKeyUp(Activity.java:2192)
            at android.view.KeyEvent.dispatch(KeyEvent.java:2729)
            at android.app.Activity.dispatchKeyEvent(Activity.java:2431)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:2033)
            at android.view.ViewRootImpl.deliverKeyEventPostIme(ViewRootImpl.java:3852)
            at android.view.ViewRootImpl.handleImeFinishedEvent(ViewRootImpl.java:3800)
            at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:2935)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:4921)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1027)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
            at dalvik.system.NativeStart.main(Native Method)
```

**Comment by aleksandr-rodikov** [comment]
Добрый день, уточните пожалуйста пользовательский сценарий для воспроизведения ошибки.
Вариант проведения платежа из [обзора](https://github.com/yandex-money/yandex-money-sdk-android#payments) к таким последствиям не приводит.

**Comment by aleksandr-rodikov** [comment]
Ошибка возникает при использовании старой версии библиотеки okhttp-2.3.0.
Актуальная на данный момент версия библиотеки okhttp-2.5.0 исправлена и ошибку не вызывает.
